language: php
php:
        - 5.4
        - 7.0
        - 7.1
        - 7.2
        - 7.3

before_script:
        - composer self-update
        - composer install


script: ./bin/phpunit
        ./bin/console security:check




        

