language: php
php:
        - 7.1
        
        

before_script:
        - curl -s http://getcomposer.org/installer | php
        - php composer.phar install --dev --prefer-dist --no-interaction


script: - phpunit --coverage-text
        - phpunit --group integration
        - security-checker security-check composer.lock
